### — Dataset Familiarization

1.	Import Pandas and load the Online Retail Excel dataset into a DataFrame named df.
2.	Display the first 5 transaction records and identify what each row represents.
3.	Display the last 10 records and inspect whether the final transactions look structurally consistent.
4.	Display 15 randomly selected transaction records to understand the variety of data.
5.	Print the total number of rows and columns in the dataset.
6.	Display all column names and identify the columns needed to analyze revenue.
7.	Display the data type of every column and identify any unsuitable data types.
8.	Determine how many rows and columns the original dataset contains.
9.	Display the first 20 product descriptions and identify examples of different products.
10.	Write a short business summary explaining what the dataset contains and what the company wants to learn.

In [7]:
import pandas as pd
data = pd.read_csv("online_retail_practice_sample.csv")
data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden
...,...,...,...,...,...,...,...,...
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,2011-04-07 12:48:00,5.10,16943.0,Spain
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2011-09-24 16:24:00,2.55,17478.0,Portugal
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2011-08-24 00:48:00,2.55,17296.0,Germany

In [8]:
data.head(15)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden
5,561166,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,3,2011-02-28 16:38:00,4.07,12343.0,Spain
6,570510,POST,POSTAGE,4,2011-07-01 00:08:00,14.40,12767.0,United Kingdom
7,574557,POST,POSTAGE,1,2011-09-23 07:36:00,21.60,13566.0,France
8,572698,21977,PACK OF 60 PINK PAISLEY CAKE CASES,2,2011-03-20 10:39:00,0.55,14765.0,Germany
9,547022,71053,WHITE METAL LANTERN,7,2011-09-14 17:41:00,4.07,15256.0,EIRE
10,567596,22633,HAND WARMER UNION JACK,15,2011-07-24 14:21:00,1.68,15220.0,France
11,572459,21212,PACK OF 72 RETROSPOT CAKE CASES,7,2011-03-08 17:47:00,0.44,12868.0,Netherlands
12,562436,POST,POSTAGE,1,2011-02-04 11:51:00,18.00,13127.0,Portugal
13,580539,22752,SET 7 BABUSHKA NESTING BOXES,8,2011-09-20 00:10:00,7.65,13152.0,Netherlands
14,540057,21730,GLASS STAR FROSTED T-LIGHT HOLDER,5,2011-04-09 14:35:00,3.40,12683.0,Spain

In [ ]:
data.tail(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1602,576798,22633,HAND WARMER UNION JACK,8,2011-03-20 15:46:00,2.10,16068.0,Australia
1603,549401,21730,GLASS STAR FROSTED T-LIGHT HOLDER,5,2011-05-25 22:09:00,3.40,13436.0,Portugal
1604,565607,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,1,2011-07-24 17:52:00,2.71,13346.0,Netherlands
1605,569476,22423,REGENCY CAKESTAND 3 TIER,4,2011-04-19 21:53:00,12.75,17314.0,Sweden
1606,C554322,21212,PACK OF 72 RETROSPOT CAKE CASES,-6,2011-08-16 02:22:00,0.55,18187.0,Sweden
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,2011-04-07 12:48:00,5.10,16943.0,Spain
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2011-09-24 16:24:00,2.55,17478.0,Portugal
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2011-08-24 00:48:00,2.55,17296.0,Germany

In [9]:
data.sample(15)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1127,556393,79323P,PINK CHERRY LIGHTS,1,2011-06-18 07:52:00,6.75,12905.0,NaN
622,C573893,22423,REGENCY CAKESTAND 3 TIER,-9,2011-07-08 07:31:00,15.30,13139.0,France
585,570604,85123A,WHITE HANGING HEART T-LIGHT HOLDER,9,2011-01-04 23:39:00,2.55,15839.0,Belgium
566,537410,79323P,PINK CHERRY LIGHTS,3,2010-12-12 01:50:00,6.75,17518.0,EIRE
984,557178,22752,SET 7 BABUSHKA NESTING BOXES,2,2011-11-20 18:07:00,6.12,13966.0,Netherlands
1274,571816,21212,PACK OF 72 RETROSPOT CAKE CASES,8,2011-11-04 23:23:00,0.55,14514.0,Netherlands
149,579741,22752,SET 7 BABUSHKA NESTING BOXES,14,2011-11-17 15:07:00,7.65,13571.0,Spain
661,572121,21730,GLASS STAR FROSTED T-LIGHT HOLDER,7,2011-01-21 15:03:00,4.25,13225.0,Sweden
1193,575471,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,10,2011-04-14 20:09:00,3.39,16418.0,France
28,C538747,71053,WHITE METAL LANTERN,-7,2011-03-17 13:09:00,2.71,17202.0,Sweden
1234,579371,21977,PACK OF 60 PINK PAISLEY CAKE CASES,6,2011-03-05 12:49:00,0.66,14965.0,Germany
877,576300,22633,HAND WARMER UNION JACK,6,2011-05-06 16:38:00,2.52,NaN,Netherlands
1209,551608,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,1,2011-07-07 06:44:00,3.39,12451.0,Sweden
724,559952,79323P,PINK CHERRY LIGHTS,5,2011-02-19 05:06:00,6.75,15034.0,Belgium
266,573371,21212,PACK OF 72 RETROSPOT CAKE CASES,5,2011-04-17 18:37:00,0.66,17889.0,Belgium

In [10]:
data.shape

(1612, 8)

In [ ]:
print("rows and cols:",data.shape)
print("total rows:",data.shape[0])
print("total cols:",data.shape[1])

rows and cols: (1612, 8)
total rows: 1612
total cols: 8

In [ ]:
print(data.columns)
(data.dtypes)

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1612 entries, 0 to 1611
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    1612 non-null   object
 1   StockCode    1612 non-null   object
 2   Description  1589 non-null   object
 3   Quantity     1612 non-null   int64
 4   InvoiceDate  1612 non-null   object
 5   UnitPrice    1612 non-null   float64
 6   CustomerID   1541 non-null   float64
 7   Country      1599 non-null   object
dtypes: float64(2), int64(1), object(5)
memory usage: 100.9+ KB

In [ ]:
print("orgn rows:",data.shape[0])
print("orgn cols:",data.shape[1])

orgn rows: 1612
orgn cols: 8

In [ ]:
data["Description"].head(20)

0                     WHITE METAL LANTERN
1       GLASS STAR FROSTED T-LIGHT HOLDER
2     KNITTED UNION FLAG HOT WATER BOTTLE
3                     WHITE METAL LANTERN
4     KNITTED UNION FLAG HOT WATER BOTTLE
5     KNITTED UNION FLAG HOT WATER BOTTLE
6                                 POSTAGE
7                                 POSTAGE
8      PACK OF 60 PINK PAISLEY CAKE CASES
9                     WHITE METAL LANTERN
10                 HAND WARMER UNION JACK
11        PACK OF 72 RETROSPOT CAKE CASES
12                                POSTAGE
13           SET 7 BABUSHKA NESTING BOXES
14      GLASS STAR FROSTED T-LIGHT HOLDER
15     PACK OF 60 PINK PAISLEY CAKE CASES
16                                POSTAGE
17               REGENCY CAKESTAND 3 TIER
18                     PINK CHERRY LIGHTS
19               REGENCY CAKESTAND 3 TIER
Name: Description, dtype: object

In [ ]:
data.isnull().sum()

InvoiceNo       0
StockCode       0
Description    23
Quantity        0
InvoiceDate     0
UnitPrice       0
CustomerID     71
Country        13
dtype: int64

In [ ]:

data.tail(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1602,576798,22633,HAND WARMER UNION JACK,8,2011-03-20 15:46:00,2.10,16068.0,Australia
1603,549401,21730,GLASS STAR FROSTED T-LIGHT HOLDER,5,2011-05-25 22:09:00,3.40,13436.0,Portugal
1604,565607,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,1,2011-07-24 17:52:00,2.71,13346.0,Netherlands
1605,569476,22423,REGENCY CAKESTAND 3 TIER,4,2011-04-19 21:53:00,12.75,17314.0,Sweden
1606,C554322,21212,PACK OF 72 RETROSPOT CAKE CASES,-6,2011-08-16 02:22:00,0.55,18187.0,Sweden
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,2011-04-07 12:48:00,5.10,16943.0,Spain
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2011-09-24 16:24:00,2.55,17478.0,Portugal
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2011-08-24 00:48:00,2.55,17296.0,Germany

In [44]:
business_summary = """
This dataset contains online retail transaction records.
It includes invoice numbers, product codes, product descriptions,
quantities, invoice dates, unit prices, customer IDs and countries.

The business can use this data to understand sales performance,
identify popular products, analyze customer purchasing patterns,
compare sales across countries and study revenue trends.

Revenue can be calculated by multiplying Quantity by UnitPrice.
Negative quantities and cancellation invoices should be examined
separately when analyzing sales and returns.
"""

print(business_summary)

This dataset contains online retail transaction records.
It includes invoice numbers, product codes, product descriptions,
quantities, invoice dates, unit prices, customer IDs and countries.

The business can use this data to understand sales performance,
identify popular products, analyze customer purchasing patterns,
compare sales across countries and study revenue trends.

Revenue can be calculated by multiplying Quantity by UnitPrice.
Negative quantities and cancellation invoices should be examined
separately when analyzing sales and returns.

### DataFrame Exploration
11.	Create a separate DataFrame containing only InvoiceNo, StockCode, Description, Quantity, UnitPrice, CustomerID and Country.
12.	Create a small DataFrame containing the first 10 transactions and save it as a separate variable.
13.	Generate descriptive statistics for numerical columns and explain what Quantity and UnitPrice reveal.
14.	Generate descriptive summaries for categorical columns such as Country and Description.
15.	Display detailed DataFrame information and identify columns with missing entries.
16.	Determine the number of distinct invoice numbers, products, countries and identified customers.
17.	Display the unique values in Country and determine how many countries appear in the dataset.
18.	Count transactions recorded for each country and display the 10 most frequent countries.
19.	Create a compact dataset summary containing row count, column count, unique products and unique invoices.
20.	Export a basic dataset profile to a CSV file for documentation.

In [ ]:
df_sel = data[[
    "InvoiceNo",
    "StockCode",
    "Description",
    "Quantity",
    "UnitPrice",
    "CustomerID",
    "Country"
]]
df_sel.head()

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,3.39,16830.0,Sweden

In [ ]:
df_first = data.head(10)
df_first

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden
5,561166,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,3,2011-02-28 16:38:00,4.07,12343.0,Spain
6,570510,POST,POSTAGE,4,2011-07-01 00:08:00,14.40,12767.0,United Kingdom
7,574557,POST,POSTAGE,1,2011-09-23 07:36:00,21.60,13566.0,France
8,572698,21977,PACK OF 60 PINK PAISLEY CAKE CASES,2,2011-03-20 10:39:00,0.55,14765.0,Germany
9,547022,71053,WHITE METAL LANTERN,7,2011-09-14 17:41:00,4.07,15256.0,EIRE

In [ ]:
data.describe()

          Quantity    UnitPrice    CustomerID
count  1612.000000  1612.000000   1541.000000
mean      7.158189     5.523189  15201.415315
std       5.890089     5.191564   1693.230069
min     -15.000000     0.000000  12305.000000
25%       4.000000     2.200000  13708.000000
50%       8.000000     3.390000  15220.000000
75%      12.000000     7.650000  16640.000000
max      15.000000    21.600000  18196.000000

In [ ]:
data.describe(include="object")

       InvoiceNo StockCode Description          InvoiceDate Country
count       1612      1612        1589                 1612    1599
unique      1574        12          22                 1599      10
top       560681      POST     POSTAGE  2011-04-07 12:48:00  France
freq           2       151         143                    2     178

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1612 entries, 0 to 1611
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    1612 non-null   object
 1   StockCode    1612 non-null   object
 2   Description  1589 non-null   object
 3   Quantity     1612 non-null   int64
 4   InvoiceDate  1612 non-null   object
 5   UnitPrice    1612 non-null   float64
 6   CustomerID   1541 non-null   float64
 7   Country      1599 non-null   object
dtypes: float64(2), int64(1), object(5)
memory usage: 100.9+ KB

In [ ]:
print("invoices:", data["InvoiceNo"].nunique())
print("products:", data["StockCode"].nunique())
print("countries:", data["Country"].nunique())
print("customers:", data["CustomerID"].nunique())

invoices: 1574
products: 12
countries: 10
customers: 1346

In [ ]:
print("Countries in the dataset:")
print(data["Country"].unique())
print("Number of countries:",data["Country"].nunique())

Countries in the dataset:
['Sweden' 'Netherlands' 'Spain' 'United Kingdom' 'France' 'Germany' 'EIRE'
 'Portugal' 'Belgium' 'Australia' nan]
Number of countries: 10

In [11]:
country = data["Country"].value_counts()
print(country.head(10))

Country
France            178
Spain             165
Australia         165
Belgium           164
Sweden            162
United Kingdom    160
Netherlands       158
EIRE              155
Portugal          147
Germany           145
Name: count, dtype: int64

In [12]:
a = pd.DataFrame({
    "Metric": [
        "Total Rows",
        "Total Columns",
        "Unique Products",
        "Unique Invoices"
    ],
    "Value": [
        data.shape[0],
        data.shape[1],
        data["StockCode"].nunique(),
        data["InvoiceNo"].nunique()
    ]
})
print(a)

            Metric  Value
0       Total Rows   1612
1    Total Columns      8
2  Unique Products     12
3  Unique Invoices   1574

In [13]:
b = pd.DataFrame({
    "Metric": [
        "Total Rows",
        "Total Columns",
        "Unique Invoices",
        "Unique Products",
        "Unique Countries",
        "Identified Customers"
    ],
    "Value": [
        data.shape[0],
        data.shape[1],
        data["InvoiceNo"].nunique(),
        data["StockCode"].nunique(),
        data["Country"].nunique(),
        data["CustomerID"].nunique()
    ]
})
b.to_csv("dataset_profile.csv", index=False)
print(b)

                 Metric  Value
0            Total Rows   1612
1         Total Columns      8
2       Unique Invoices   1574
3       Unique Products     12
4      Unique Countries     10
5  Identified Customers   1346

### Data Selection and Filtering

21.	Select and display only InvoiceNo and InvoiceDate for all transactions.
22.	Retrieve a transaction at a specified row position using iloc and explain the difference between row position and index label.
23.	Use loc to retrieve selected columns for a chosen range of index labels.
24.	Filter transactions where Quantity is greater than 10.
25.	Find transactions where UnitPrice is greater than £50.
26.	Retrieve all transactions belonging to a specified country using a Boolean condition.
27.	Use isin to find transactions from the five countries with the highest transaction counts.
28.	Use between to retrieve transactions with quantities between 5 and 20 inclusive.
29.	Use query to find transactions where Quantity is greater than 10 and UnitPrice is greater than £5.
30.	Sort transactions by UnitPrice in descending order and display the 20 highest unit-price

In [ ]:
#1
data[['InvoiceNo', 'InvoiceDate']]

     InvoiceNo          InvoiceDate
0       570338  2011-09-15 15:26:00
1       574674  2011-06-05 08:10:00
2       545052  2011-07-24 03:45:00
3       567005  2011-09-04 16:55:00
4       573512  2011-02-23 13:40:00
...        ...                  ...
1607    546730  2011-09-20 00:21:00
1608    556479  2011-11-13 09:05:00
1609   C541876  2011-04-07 12:48:00
1610    553299  2011-09-24 16:24:00
1611    537515  2011-08-24 00:48:00

[1612 rows x 2 columns]

In [ ]:
#2
data.iloc[5]

InvoiceNo                                   561166
StockCode                                   84029G
Description    KNITTED UNION FLAG HOT WATER BOTTLE
Quantity                                         3
InvoiceDate                    2011-02-28 16:38:00
UnitPrice                                     4.07
CustomerID                                 12343.0
Country                                      Spain
Name: 5, dtype: object

In [ ]:
#3
data.loc[0:10, ['InvoiceNo', 'InvoiceDate', 'Quantity']]

   InvoiceNo          InvoiceDate  Quantity
0     570338  2011-09-15 15:26:00         7
1     574674  2011-06-05 08:10:00        14
2     545052  2011-07-24 03:45:00         0
3     567005  2011-09-04 16:55:00        12
4     573512  2011-02-23 13:40:00        15
5     561166  2011-02-28 16:38:00         3
6     570510  2011-07-01 00:08:00         4
7     574557  2011-09-23 07:36:00         1
8     572698  2011-03-20 10:39:00         2
9     547022  2011-09-14 17:41:00         7
10    567596  2011-07-24 14:21:00        15

In [ ]:
#4
data[data['Quantity'] > 10]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden
10,567596,22633,HAND WARMER UNION JACK,15,2011-07-24 14:21:00,1.68,15220.0,France
18,580659,79323P,PINK CHERRY LIGHTS,15,2011-06-11 21:15:00,8.10,18019.0,Sweden
...,...,...,...,...,...,...,...,...
1593,560762,21730,GLASS STAR FROSTED T-LIGHT HOLDER,11,2011-07-22 02:33:00,4.25,15530.0,Belgium
1595,564607,POST,POSTAGE,15,2011-07-02 04:57:00,18.00,13500.0,Netherlands
1601,540834,POST,POSTAGE,14,2011-01-26 11:06:00,21.60,13594.0,United Kingdom
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE

In [ ]:
#5
data[data['UnitPrice'] > 50]

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

In [ ]:
#6
data[data['Country'] == 'France']

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
7,574557,POST,POSTAGE,1,2011-09-23 07:36:00,21.60,13566.0,France
10,567596,22633,HAND WARMER UNION JACK,15,2011-07-24 14:21:00,1.68,15220.0,France
17,564700,22423,REGENCY CAKESTAND 3 TIER,1,2011-11-29 05:14:00,12.75,14488.0,France
19,553325,22423,REGENCY CAKESTAND 3 TIER,8,2011-02-22 21:06:00,10.20,16854.0,France
20,563118,85123A,WHITE HANGING HEART T-LIGHT HOLDER,1,2011-11-15 22:14:00,2.04,14466.0,France
...,...,...,...,...,...,...,...,...
1568,C571045,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,-1,2011-12-07 12:08:00,3.39,14746.0,France
1580,536758,22633,HAND WARMER UNION JACK,5,2011-01-10 10:03:00,1.68,14476.0,France
1581,552090,21730,GLASS STAR FROSTED T-LIGHT HOLDER,9,2011-01-19 21:03:00,5.10,13181.0,France
1591,560681,71053,WHITE METAL LANTERN,15,2011-09-26 08:49:00,4.07,16346.0,France
1597,C555041,79323P,PINK CHERRY LIGHTS,-14,2011-11-06 12:02:00,6.75,14111.0,France

In [ ]:
#7
top_5_countries = data['Country'].value_counts().head(5).index
data[data['Country'].isin(top_5_countries)]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden
5,561166,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,3,2011-02-28 16:38:00,4.07,12343.0,Spain
...,...,...,...,...,...,...,...,...
1602,576798,22633,HAND WARMER UNION JACK,8,2011-03-20 15:46:00,2.10,16068.0,Australia
1605,569476,22423,REGENCY CAKESTAND 3 TIER,4,2011-04-19 21:53:00,12.75,17314.0,Sweden
1606,C554322,21212,PACK OF 72 RETROSPOT CAKE CASES,-6,2011-08-16 02:22:00,0.55,18187.0,Sweden
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,2011-04-07 12:48:00,5.10,16943.0,Spain

In [ ]:
#8
data[data['Quantity'].between(5,20)]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden
9,547022,71053,WHITE METAL LANTERN,7,2011-09-14 17:41:00,4.07,15256.0,EIRE
...,...,...,...,...,...,...,...,...
1603,549401,21730,GLASS STAR FROSTED T-LIGHT HOLDER,5,2011-05-25 22:09:00,3.40,13436.0,Portugal
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2011-09-24 16:24:00,2.55,17478.0,Portugal
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2011-08-24 00:48:00,2.55,17296.0,Germany

In [ ]:
#9
data.query("Quantity > 10 and UnitPrice > 5")

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
18,580659,79323P,PINK CHERRY LIGHTS,15,2011-06-11 21:15:00,8.10,18019.0,Sweden
31,550785,22423,REGENCY CAKESTAND 3 TIER,15,2011-09-25 21:14:00,12.75,16898.0,Netherlands
38,566325,22423,REGENCY CAKESTAND 3 TIER,11,2011-01-14 18:07:00,10.20,13528.0,Sweden
69,566686,22423,REGENCY CAKESTAND 3 TIER,13,2011-06-14 08:46:00,12.75,15782.0,United Kingdom
89,577425,22752,SET 7 BABUSHKA NESTING BOXES,14,2011-11-16 02:46:00,6.12,16327.0,Sweden
...,...,...,...,...,...,...,...,...
1575,547919,22423,REGENCY CAKESTAND 3 TIER,11,2011-04-09 18:38:00,12.75,16277.0,EIRE
1587,572765,21730,GLASS STAR FROSTED T-LIGHT HOLDER,15,2010-12-12 17:20:00,5.10,17421.0,Belgium
1595,564607,POST,POSTAGE,15,2011-07-02 04:57:00,18.00,13500.0,Netherlands
1601,540834,POST,POSTAGE,14,2011-01-26 11:06:00,21.60,13594.0,United Kingdom
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE

In [ ]:
#10
data.sort_values(by='UnitPrice', ascending=False).head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1248,565100,POST,POSTAGE,14,2011-11-25 20:27:00,21.6,13873.0,Australia
1253,573477,POST,POSTAGE,8,2011-04-22 14:47:00,21.6,18172.0,EIRE
49,557529,POST,POSTAGE,7,2011-08-19 06:38:00,21.6,17690.0,Australia
465,569506,POST,POSTAGE,6,2011-11-08 11:22:00,21.6,16513.0,Australia
932,C561717,POST,POSTAGE,-11,2011-11-22 12:10:00,21.6,15675.0,Netherlands
1528,565108,POST,POSTAGE,10,2011-03-29 08:51:00,21.6,16176.0,France
1560,567925,POST,POSTAGE,4,2011-01-20 13:21:00,21.6,17041.0,France
101,573603,POST,POSTAGE,8,2011-03-16 11:27:00,21.6,14863.0,Australia
764,572968,POST,POSTAGE,6,2011-07-22 19:28:00,21.6,16251.0,Germany
502,C543573,POST,POSTAGE,-15,2011-05-26 09:37:00,21.6,17799.0,Spain
833,574836,POST,POSTAGE,2,2011-05-21 21:25:00,21.6,14562.0,EIRE
501,552616,POST,POSTAGE,6,2011-05-15 13:37:00,21.6,12473.0,France
752,549960,POST,POSTAGE,15,2011-10-20 05:17:00,21.6,14865.0,Australia
353,570905,POST,POSTAGE,12,2011-05-18 16:49:00,21.6,NaN,United Kingdom
359,547600,POST,POSTAGE,8,2011-10-08 10:31:00,21.6,14477.0,Portugal
456,578392,POST,POSTAGE,1,2010-12-16 14:40:00,21.6,15550.0,Germany
1601,540834,POST,POSTAGE,14,2011-01-26 11:06:00,21.6,13594.0,United Kingdom
7,574557,POST,POSTAGE,1,2011-09-23 07:36:00,21.6,13566.0,France
617,540834,POST,POSTAGE,14,2011-01-26 11:06:00,21.6,13594.0,United Kingdom
893,565522,POST,POSTAGE,1,2011-08-02 16:33:00,21.6,13623.0,United Kingdom

### Data Transformation and Management
31.	Create a working copy of the original DataFrame and retain the untouched source as df_raw.
32.	Rename the Description column to ProductDescription in your working copy.
33.	Create a Revenue column by multiplying Quantity by UnitPrice, preserving the original signed quantity.
34.	Create a TransactionType column to classify records as cancellation, return, positive sale or other/invalid, using documented rules.
35.	Create an IsIdentifiedCustomer column that indicates whether CustomerID is available.
36.	Convert InvoiceDate to a proper Pandas datetime data type.
37.	Convert InvoiceNo, StockCode and Country to suitable string data types.
38.	Reorder columns so transaction identifiers and dates appear before product, customer and financial information.
39.	Sort the working dataset by InvoiceDate and then by InvoiceNo.
40.	Reset the DataFrame index after sorting and verify that the new index is sequential.

In [17]:
#1
df_raw = data.copy()
data = df_raw.copy()
data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden
...,...,...,...,...,...,...,...,...
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,2011-04-07 12:48:00,5.10,16943.0,Spain
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2011-09-24 16:24:00,2.55,17478.0,Portugal
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2011-08-24 00:48:00,2.55,17296.0,Germany

In [20]:
#2
data = df_raw.copy()
data = data.rename(columns={'Description': 'ProductDescription'})
data.head()

,InvoiceNo,StockCode,ProductDescription,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden

In [21]:
#3
data['Revenue'] = data['Quantity'] * data['UnitPrice']
data.head()

,InvoiceNo,StockCode,ProductDescription,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden,28.49
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden,59.50
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands,0.00
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain,40.68
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden,50.85

In [22]:
#4
import numpy as np
data['TransactionType'] = np.select(
    [
        data['InvoiceNo'].astype(str).str.startswith('C'),
        data['Quantity'] < 0,
        data['Quantity'] > 0
    ],
    [
        'Cancellation',
        'Return',
        'Positive Sale'
    ],
    default='Other/Invalid'
)
data['TransactionType'].value_counts()

TransactionType
Positive Sale    1498
Cancellation      105
Other/Invalid       9
Name: count, dtype: int64

In [23]:
#5
data['IsIdentifiedCustomer'] = data['CustomerID'].notna()
data.head()

,InvoiceNo,StockCode,ProductDescription,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,TransactionType,IsIdentifiedCustomer
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden,28.49,Positive Sale,True
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden,59.50,Positive Sale,True
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands,0.00,Other/Invalid,True
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain,40.68,Positive Sale,True
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden,50.85,Positive Sale,True

In [24]:
data['InvoiceDate'] = pd.to_datetime(data['InvoiceDate'])
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1612 entries, 0 to 1611
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   InvoiceNo             1612 non-null   object
 1   StockCode             1612 non-null   object
 2   ProductDescription    1589 non-null   object
 3   Quantity              1612 non-null   int64
 4   InvoiceDate           1612 non-null   datetime64[ns]
 5   UnitPrice             1612 non-null   float64
 6   CustomerID            1541 non-null   float64
 7   Country               1599 non-null   object
 8   Revenue               1612 non-null   float64
 9   TransactionType       1612 non-null   object
 10  IsIdentifiedCustomer  1612 non-null   bool
dtypes: bool(1), datetime64[ns](1), float64(3), int64(1), object(5)
memory usage: 127.6+ KB

In [25]:
data['InvoiceNo'] = data['InvoiceNo'].astype('string')
data['StockCode'] = data['StockCode'].astype('string')
data['Country'] = data['Country'].astype('string')
data.dtypes

InvoiceNo               string[python]
StockCode               string[python]
ProductDescription              object
Quantity                         int64
InvoiceDate             datetime64[ns]
UnitPrice                      float64
CustomerID                     float64
Country                 string[python]
Revenue                        float64
TransactionType                 object
IsIdentifiedCustomer              bool
dtype: object

In [26]:
cols = [
    'InvoiceNo', 'InvoiceDate', 'StockCode', 'ProductDescription',
    'CustomerID', 'Country', 'Quantity', 'UnitPrice', 'Revenue',
    'TransactionType', 'IsIdentifiedCustomer'
]
data = data[[col for col in cols if col in data.columns]]
data.head()

,InvoiceNo,InvoiceDate,StockCode,ProductDescription,CustomerID,Country,Quantity,UnitPrice,Revenue,TransactionType,IsIdentifiedCustomer
0,570338,2011-09-15 15:26:00,71053,WHITE METAL LANTERN,16640.0,Sweden,7,4.07,28.49,Positive Sale,True
1,574674,2011-06-05 08:10:00,21730,GLASS STAR FROSTED T-LIGHT HOLDER,17154.0,Sweden,14,4.25,59.50,Positive Sale,True
2,545052,2011-07-24 03:45:00,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,16783.0,Netherlands,0,3.39,0.00,Other/Invalid,True
3,567005,2011-09-04 16:55:00,71053,WHITE METAL LANTERN,14222.0,Spain,12,3.39,40.68,Positive Sale,True
4,573512,2011-02-23 13:40:00,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,16830.0,Sweden,15,3.39,50.85,Positive Sale,True

In [27]:
data = data.sort_values(by=['InvoiceDate', 'InvoiceNo'])
data.head()

,InvoiceNo,InvoiceDate,StockCode,ProductDescription,CustomerID,Country,Quantity,UnitPrice,Revenue,TransactionType,IsIdentifiedCustomer
1523,569444,2010-12-01 00:05:00,71053,WHITE METAL LANTERN,13845.0,Germany,15,3.39,50.85,Positive Sale,True
122,C543863,2010-12-01 02:26:00,84406B,CREAM CUPID HEARTS COAT HANGER,14319.0,France,-13,2.75,-35.75,Cancellation,True
409,568184,2010-12-01 03:57:00,84406B,CREAM CUPID HEARTS COAT HANGER,15058.0,France,3,2.20,6.60,Positive Sale,True
78,C551232,2010-12-01 06:06:00,71053,WHITE METAL LANTERN,12472.0,Spain,-7,4.07,-28.49,Cancellation,True
1312,536850,2010-12-01 21:38:00,22423,REGENCY CAKESTAND 3 TIER,12972.0,Sweden,9,10.20,91.80,Positive Sale,True

In [28]:
data = data.reset_index(drop=True)
print(data.index)
print(data.index.is_unique)
print(data.index.equals(pd.RangeIndex(start=0, stop=len(data))))

RangeIndex(start=0, stop=1612, step=1)
True
True

###Data Quality and Missing-Value Management
41.	Calculate the missing-value count and missing-value percentage for every column.
42.	Identify the columns with the highest percentage of missing values and rank them.
43.	Display all records where CustomerID is missing and determine how many transactions are affected.
44.	Display records where Description is missing or contains only whitespace.
45.	Create a missing-value report with column name, missing count, non-missing count and missing percentage.
46.	Identify exact duplicate rows and report the duplicate count before removing anything.
47.	Remove exact duplicate rows from a working copy and verify how many records remain.
48.	Investigate repeated InvoiceNo and StockCode combinations without automatically deleting them, since multiple lines may be legitimate.
49.	Handle missing Description values using a documented strategy and explain why missing CustomerID values should not be filled with invented IDs.
50.	Create a data-quality report comparing row counts, missing values and duplicate counts before and after cleaning.

In [29]:
#1
missing_count = data.isnull().sum()
missing_percentage = (missing_count / len(data)) * 100

missing_report = pd.DataFrame({
    'MissingCount': missing_count,
    'MissingPercentage': missing_percentage
})
missing_report

                      MissingCount  MissingPercentage
InvoiceNo                        0           0.000000
InvoiceDate                      0           0.000000
StockCode                        0           0.000000
ProductDescription              23           1.426799
CustomerID                      71           4.404467
Country                         13           0.806452
Quantity                         0           0.000000
UnitPrice                        0           0.000000
Revenue                          0           0.000000
TransactionType                  0           0.000000
IsIdentifiedCustomer             0           0.000000

In [30]:
missing_report.sort_values(
    by='MissingPercentage',
    ascending=False
)

                      MissingCount  MissingPercentage
CustomerID                      71           4.404467
ProductDescription              23           1.426799
Country                         13           0.806452
StockCode                        0           0.000000
InvoiceDate                      0           0.000000
InvoiceNo                        0           0.000000
Quantity                         0           0.000000
UnitPrice                        0           0.000000
Revenue                          0           0.000000
TransactionType                  0           0.000000
IsIdentifiedCustomer             0           0.000000

In [31]:
data[data['CustomerID'].isna()]

,InvoiceNo,InvoiceDate,StockCode,ProductDescription,CustomerID,Country,Quantity,UnitPrice,Revenue,TransactionType,IsIdentifiedCustomer
14,549594,2010-12-03 13:48:00,POST,POSTAGE,NaN,Belgium,13,18.00,234.00,Positive Sale,False
101,C569164,2010-12-22 13:25:00,71053,WHITE METAL LANTERN,NaN,Germany,-5,4.07,-20.35,Cancellation,False
125,550375,2010-12-29 06:33:00,85123A,WHITE HANGING HEART T-LIGHT HOLDER,NaN,Spain,6,2.55,15.30,Positive Sale,False
146,561467,2011-01-05 07:47:00,POST,POSTAGE,NaN,Australia,14,18.00,252.00,Positive Sale,False
154,573565,2011-01-08 03:20:00,84406B,CREAM CUPID HEARTS COAT HANGER,NaN,Netherlands,12,2.20,26.40,Positive Sale,False
...,...,...,...,...,...,...,...,...,...,...,...
1516,540081,2011-11-18 20:23:00,79323P,PINK CHERRY LIGHTS,NaN,United Kingdom,2,0.00,0.00,Positive Sale,False
1549,560412,2011-11-24 12:27:00,21977,PACK OF 60 PINK PAISLEY CAKE CASES,NaN,Portugal,9,0.44,3.96,Positive Sale,False
1558,542958,2011-11-26 20:13:00,79323P,PINK CHERRY LIGHTS,NaN,Netherlands,11,6.75,74.25,Positive Sale,False
1575,568423,2011-12-01 13:25:00,22423,REGENCY CAKESTAND 3 TIER,NaN,EIRE,11,10.20,112.20,Positive Sale,False
1582,550723,2011-12-02 18:44:00,79323P,PINK CHERRY LIGHTS,NaN,Belgium,15,6.75,101.25,Positive Sale,False

In [34]:
data[data['ProductDescription'].isna() | data['ProductDescription'].str.strip().eq('')]

,InvoiceNo,InvoiceDate,StockCode,ProductDescription,CustomerID,Country,Quantity,UnitPrice,Revenue,TransactionType,IsIdentifiedCustomer
28,539070,2010-12-06 21:35:00,71053,NaN,14099.0,Australia,4,3.39,13.56,Positive Sale,True
31,559978,2010-12-08 10:14:00,85123A,NaN,14249.0,Germany,14,2.04,28.56,Positive Sale,True
92,556807,2010-12-21 05:17:00,71053,NaN,15636.0,Belgium,11,3.39,37.29,Positive Sale,True
149,572899,2011-01-06 07:02:00,79323P,NaN,14260.0,Germany,11,5.40,59.40,Positive Sale,True
167,547347,2011-01-10 23:47:00,21730,NaN,NaN,Portugal,10,3.40,34.00,Positive Sale,False
180,542751,2011-01-14 08:14:00,21730,NaN,NaN,United Kingdom,7,4.25,29.75,Positive Sale,False
240,561900,2011-01-28 07:58:00,22633,NaN,14208.0,Belgium,3,2.10,6.30,Positive Sale,True
306,537284,2011-02-12 18:56:00,21977,NaN,14195.0,Australia,9,0.44,3.96,Positive Sale,True
431,554099,2011-03-12 12:39:00,22633,NaN,13832.0,United Kingdom,2,2.10,4.20,Positive Sale,True
654,551929,2011-04-30 01:35:00,21977,NaN,13115.0,Germany,15,0.55,8.25,Positive Sale,True
662,C566354,2011-05-01 18:46:00,71053,NaN,17168.0,United Kingdom,-4,2.71,-10.84,Cancellation,True
727,574284,2011-05-19 16:30:00,22423,NaN,12445.0,Netherlands,5,12.75,63.75,Positive Sale,True
782,552366,2011-06-01 15:42:00,POST,NaN,12632.0,Spain,2,18.00,36.00,Positive Sale,True
821,572385,2011-06-10 16:31:00,79323P,NaN,15755.0,Netherlands,1,8.10,8.10,Positive Sale,True
923,561823,2011-07-02 06:23:00,21977,NaN,16012.0,United Kingdom,12,0.66,7.92,Positive Sale,True
936,C547433,2011-07-04 20:48:00,POST,NaN,16058.0,Portugal,-2,18.00,-36.00,Cancellation,True
1084,537522,2011-08-12 01:07:00,22423,NaN,16779.0,EIRE,14,12.75,178.50,Positive Sale,True
1146,580090,2011-08-24 14:53:00,21212,NaN,14881.0,France,10,0.55,5.50,Positive Sale,True
1171,550113,2011-08-30 04:01:00,21977,NaN,15250.0,Spain,6,0.66,3.96,Positive Sale,True
1278,564709,2011-09-23 14:12:00,22752,NaN,14460.0,EIRE,5,6.12,30.60,Positive Sale,True
1323,578854,2011-10-04 13:55:00,71053,NaN,15358.0,Sweden,7,3.39,23.73,Positive Sale,True
1389,569468,2011-10-24 13:30:00,22752,NaN,16229.0,Belgium,15,7.65,114.75,Positive Sale,True
1579,565746,2011-12-01 23:38:00,84029G,NaN,16066.0,United Kingdom,3,3.39,10.17,Positive Sale,True

In [35]:
missing_report = pd.DataFrame({
    'ColumnName': data.columns,
    'MissingCount': data.isnull().sum().values,
    'NonMissingCount': data.notnull().sum().values,
    'MissingPercentage': (data.isnull().mean() * 100).values
})
missing_report

              ColumnName  MissingCount  NonMissingCount  MissingPercentage
0              InvoiceNo             0             1612           0.000000
1            InvoiceDate             0             1612           0.000000
2              StockCode             0             1612           0.000000
3     ProductDescription            23             1589           1.426799
4             CustomerID            71             1541           4.404467
5                Country            13             1599           0.806452
6               Quantity             0             1612           0.000000
7              UnitPrice             0             1612           0.000000
8                Revenue             0             1612           0.000000
9        TransactionType             0             1612           0.000000
10  IsIdentifiedCustomer             0             1612           0.000000

In [36]:
data.duplicated().sum()

np.int64(12)

In [37]:
data_clean = data.drop_duplicates().copy()
print("Records before cleaning:", len(data))
print("Records after cleaning:", len(data_clean))

Records before cleaning: 1612
Records after cleaning: 1600

In [38]:
data.groupby(['InvoiceNo', 'StockCode']).size().reset_index(name='Count').query('Count > 1')

     InvoiceNo StockCode  Count
46      537515    85123A      2
164     540834      POST      2
337     546048    85123A      2
359     546730     21730      2
454     549401     21730      2
593     553299    85123A      2
706     556479     22423      2
981     565607    84029G      2
1100    569476     22423      2
1274    574232     71053      2
1373    576798     22633      2
1504   C541876     21730      2
1547   C554322     21212      2

In [41]:
data_clean['ProductDescription'] = data_clean['ProductDescription'].replace(r'^\s*$', pd.NA, regex=True)
data_clean['ProductDescription'] = data_clean['ProductDescription'].fillna('Unknown Description')
data_clean['CustomerID'].isna().sum()

np.int64(71)

In [42]:
data_quality_report = pd.DataFrame({
    'Metric': [
        'Row Count',
        'Missing Values',
        'Exact Duplicate Rows'
    ],
    'Before Cleaning': [
        len(data),
        data.isna().sum().sum(),
        data.duplicated().sum()
    ],
    'After Cleaning': [
        len(data_clean),
        data_clean.isna().sum().sum(),
        data_clean.duplicated().sum()
    ]
})
data_quality_report

                 Metric  Before Cleaning  After Cleaning
0             Row Count             1612            1600
1        Missing Values              107              84
2  Exact Duplicate Rows               12               0

In [43]:
data_quality_report.to_csv("data_quality_report.csv",index=False)
print("Data quality report saved succcessfully!")

Data quality report saved succcessfully!